language: php
sudo: false

php:
  - 5.6

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - drush make --prepare-install build-panopolicious.make ../vih.dk --yes
  - cd ../vih.dk
  - chmod -R 777 sites/all/modules
  - php -d sendmail_path=/dev/null `which drush` si panopoly --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="Panopolicious" --yes
  - drush cc all --yes
  - cd ../panopolicious

script: 
  - test -d ../vih.dk/sites/all/modules/contrib
  - test -d ../vih.dk/profiles/panopoly
